name: Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx lerna bootstrap --hoist
      - run: npx lerna run test
        env:
          CI: true
      # We want to ensure there are no issues the demo builds as well
      - run: npx lerna run docs
      - uses: actions/upload-artifact@v2
        with:
          name: Cypress Test Recording
          path: packages/style-kit/cypress/videos/
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress Test Screenshots
          path: packages/style-kit/cypress/screenshots/
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress Failure Diffs
          path: packages/style-kit/cypress/snapshots/
      - run: npx lerna run build
