name: Release SDK

on:
  push:
    tags:
      - 'releases/style-kit/**'
      - '!releases/style-kit/**-beta'

jobs:
  create_style_kit_release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx lerna bootstrap --hoist
      - run: npx lerna run test
        env:
          CI: true
      - run: npx lerna run build --scope @meeco/style-kit
      - name: Publish NPM
        run: |
          npx lerna exec --scope @meeco/style-kit -- npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npx lerna exec --scope @meeco/style-kit -- npm config set scope "@meeco"
          npx lerna exec --scope @meeco/style-kit -- npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
