name: Update Documentation

on:
  push:
    branches:
      - master
jobs:
  update_documentation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx lerna bootstrap --hoist
      # This step is required as long as we are using typedoc beta which we are to support
      # library mode
      - run: cd packages/sdk && cd ../../
      - run: npm run docs
      # Should run *before* the github pages deploy as that runs its own commit
      - name: Push OCLIF Generated CLI Readme
        uses: EndBug/add-and-commit@v4
        # https://github.com/marketplace/actions/add-commit
        with:
          add: 'packages/cli/README.md'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Auto-update CLI documentation'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      - name: Deploy SDK docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
